import { supabase } from './supabase.js';

const desktop=document.getElementById('desktop');
const windows=[...document.querySelectorAll('.app-window')];let z=20;
const openWindow=id=>{const el=document.getElementById(id);if(!el)return;el.classList.remove('hidden');z++;el.style.zIndex=z;if(id==='library')loadLibrary()};
const closeWindow=id=>document.getElementById(id)?.classList.add('hidden');
const openReader=id=>{if(id)location.href=`read.html?id=${encodeURIComponent(id)}`};
document.addEventListener('click',e=>{const t=e.target.closest('[data-window]');if(t){e.preventDefault();openWindow(t.dataset.window)}const c=e.target.closest('[data-close]');if(c){e.preventDefault();closeWindow(c.dataset.close)}});
windows.forEach(w=>w.addEventListener('mousedown',()=>{z++;w.style.zIndex=z}));

function updateClock(){const n=new Date();const time=new Intl.DateTimeFormat('en-IN',{hour:'numeric',minute:'2-digit',hour12:true}).format(n);const date=new Intl.DateTimeFormat('en-IN',{weekday:'long',day:'numeric',month:'long'}).format(n);document.getElementById('clockTime')?.replaceChildren(time);document.getElementById('menuTime')?.replaceChildren(time);document.getElementById('clockDate')?.replaceChildren(date)}updateClock();setInterval(updateClock,1000);

const lang=document.getElementById('languageToggle');if(lang)lang.addEventListener('click',()=>{const bn=document.documentElement.lang!=='bn';document.documentElement.lang=bn?'bn':'en';lang.textContent=bn?'বাংলা / EN':'EN / বাংলা'});
const wallpapers={main:"url('assets/wallpapers/kolpotuli-main.png')",dusk:"url('assets/wallpapers/kolpotuli-dusk.svg')",paper:"url('assets/wallpapers/kolpotuli-paper.svg')"};
const saved=localStorage.getItem('kolpotuli-wallpaper')||'main';
if(desktop){desktop.style.setProperty('--wallpaper',wallpapers[saved]||wallpapers.main);desktop.style.setProperty('background-image',`linear-gradient(180deg,rgba(4,20,32,.08),rgba(4,20,32,.03)),${wallpapers[saved]||wallpapers.main}`,'important')}
document.querySelectorAll('[data-wallpaper]').forEach(b=>b.addEventListener('click',()=>{const k=b.dataset.wallpaper;if(!wallpapers[k]||!desktop)return;desktop.style.setProperty('--wallpaper',wallpapers[k]);desktop.style.setProperty('background-image',k==='main'?`linear-gradient(180deg,rgba(4,20,32,.08),rgba(4,20,32,.03)),${wallpapers[k]}`:wallpapers[k],'important');localStorage.setItem('kolpotuli-wallpaper',k);document.querySelectorAll('[data-wallpaper]').forEach(x=>x.classList.toggle('selected',x===b))}));document.querySelector(`[data-wallpaper="${saved}"]`)?.classList.add('selected');

const style=document.createElement('style');style.textContent=`.settings-window{width:520px;left:50%;top:12%;transform:translateX(-50%);z-index:50}.settings-window h2{margin:0;color:var(--navy);font-size:25px}.settings-intro{margin:5px 0 22px;opacity:.65}.settings-window h3{font-size:12px;letter-spacing:.08em;text-transform:uppercase;margin:18px 0 10px;color:var(--teal)}.wallpaper-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.wallpaper-card{padding:8px;border:1px solid rgba(20,32,42,.12);border-radius:14px;background:rgba(255,255,255,.45);color:var(--ink);text-align:left;box-shadow:0 8px 20px rgba(20,32,42,.08);transition:.18s}.wallpaper-card:hover,.wallpaper-card.selected{transform:translateY(-3px);border-color:var(--gold);box-shadow:0 12px 24px rgba(20,32,42,.14)}.wallpaper-preview{display:block;height:78px;border-radius:9px;margin-bottom:8px;background-size:cover;background-position:center}.main-preview{background-image:url('../assets/wallpapers/kolpotuli-main.png')}.dusk-preview{background-image:url('../assets/wallpapers/kolpotuli-dusk.svg')}.paper-preview{background-image:url('../assets/wallpapers/kolpotuli-paper.svg')}.wallpaper-card strong,.wallpaper-card small{display:block}.wallpaper-card strong{font-size:12px}.wallpaper-card small{font-size:10px;opacity:.62;margin-top:2px}.db-thumb{background-size:cover;background-position:center;background-color:rgba(255,255,255,.08)}.library-empty{padding:25px;opacity:.6;text-align:center}.content-card{position:relative;cursor:pointer}.save-content{position:absolute;right:10px;top:150px;border:0;border-radius:50%;width:30px;height:30px;background:rgba(20,40,61,.82);color:#fff;cursor:pointer}.search-results{position:absolute;z-index:80;left:50%;top:55px;transform:translateX(-50%);width:min(560px,calc(100vw - 30px));background:rgba(255,250,238,.97);border-radius:16px;padding:12px;box-shadow:0 20px 60px rgba(0,0,0,.3);display:none}.search-results.show{display:block}.search-result{display:flex;gap:10px;align-items:center;width:100%;border:0;background:transparent;text-align:left;padding:10px;border-radius:10px;cursor:pointer}.search-result:hover{background:rgba(20,40,61,.07)}.search-result small{display:block;opacity:.55}`;document.head.appendChild(style);

const play=document.querySelector('.music-controls .play');if(play)play.addEventListener('click',()=>{play.classList.toggle('playing');play.textContent=play.classList.contains('playing')?'Ⅱ':'▶'});
const esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));
async function currentUser(){const{data:{user}}=await supabase.auth.getUser();return user}
async function loadContent(){const{data,error}=await supabase.from('content_items').select('id,type,title,excerpt,cover_image_url,language,featured,read_time_minutes,published_at').eq('status','published').order('featured',{ascending:false}).order('published_at',{ascending:false}).limit(60);if(error){console.warn('Kolpotuli content load:',error.message);return}window.kolpotuliContent=data||[];const grouped={story:[],art:[],blog:[]};(data||[]).forEach(item=>grouped[item.type]?.push(item));renderContent('stories',grouped.story,'story');renderContent('art',grouped.art,'art');renderBlogs(grouped.blog);await renderRecent()}
function renderContent(windowId,items,type){const win=document.getElementById(windowId),grid=win?.querySelector('.card-grid');if(!grid)return;if(!items.length){grid.innerHTML='<div class="library-empty">No published content yet.</div>';return}grid.innerHTML=items.slice(0,12).map(x=>`<article class="content-card" data-content-id="${esc(x.id)}"><div class="thumb db-thumb" style="${x.cover_image_url?`background-image:url('${esc(x.cover_image_url)}')`:''}"></div><h3>${esc(x.title)}</h3><p>${esc(type==='story'?'Story':'Artwork')}${x.read_time_minutes?` · ${x.read_time_minutes} min`:''}</p><button class="save-content" data-save="${esc(x.id)}" aria-label="Save">♡</button></article>`).join('');grid.querySelectorAll('[data-content-id]').forEach(card=>card.addEventListener('click',e=>{if(e.target.closest('[data-save]'))return;markOpened(card.dataset.contentId);openReader(card.dataset.contentId)}));grid.querySelectorAll('[data-save]').forEach(b=>b.addEventListener('click',async e=>{e.stopPropagation();await toggleFavorite(b.dataset.save,b)}))}
function renderBlogs(items){const links=document.querySelector('.blog-links');if(!links)return;if(!items.length){links.innerHTML='<span style="opacity:.55">No published blogs yet.</span>';return}links.innerHTML=items.slice(0,8).map(x=>`<button data-content-id="${esc(x.id)}">${esc(x.title)}</button>`).join('');links.querySelectorAll('[data-content-id]').forEach(b=>b.addEventListener('click',()=>{markOpened(b.dataset.contentId);openReader(b.dataset.contentId)}))}
async function renderRecent(){const box=document.querySelector('.recent-widget');if(!box)return;const user=await currentUser();if(!user){box.innerHTML='<div class="widget-kicker">RECENTLY OPENED</div><div class="widget-sub">Sign in to keep your history.</div>';return}const{data}=await supabase.from('recently_opened').select('opened_at,content_items(id,title,type)').eq('user_id',user.id).order('opened_at',{ascending:false}).limit(3);box.innerHTML='<div class="widget-kicker">RECENTLY OPENED</div>'+((data||[]).filter(x=>x.content_items).map(x=>`<button class="recent-item" data-content-id="${esc(x.content_items.id)}"><span>${x.content_items.type==='art'?'◆':x.content_items.type==='blog'?'▤':'▣'}</span><span><strong>${esc(x.content_items.title)}</strong><small>${esc(x.content_items.type)}</small></span></button>`).join('')||'<div class="widget-sub">Nothing opened yet.</div>');box.querySelectorAll('[data-content-id]').forEach(b=>b.addEventListener('click',()=>openReader(b.dataset.contentId)))}
async function markOpened(contentId){const user=await currentUser();if(!user)return;await supabase.from('recently_opened').upsert({user_id:user.id,content_id:contentId,opened_at:new Date().toISOString()},{onConflict:'user_id,content_id'});renderRecent()}
async function toggleFavorite(contentId,button){const user=await currentUser();if(!user){window.dispatchEvent(new Event('kolpotuli-open-auth'));return}const{data}=await supabase.from('favorites').select('content_id').eq('user_id',user.id).eq('content_id',contentId).maybeSingle();if(data){await supabase.from('favorites').delete().eq('user_id',user.id).eq('content_id',contentId);button.textContent='♡'}else{await supabase.from('favorites').insert({user_id:user.id,content_id:contentId});button.textContent='♥'}loadLibrary()}
async function loadLibrary(){const user=await currentUser(),area=document.querySelector('#library .list-area');if(!area)return;if(!user){area.innerHTML='<div class="library-empty">Sign in to use your personal Library.</div>';return}const{data,error}=await supabase.from('favorites').select('content_id,content_items(id,title,type,read_time_minutes)').eq('user_id',user.id);if(error){area.innerHTML='<div class="library-empty">Unable to load your library.</div>';return}area.innerHTML=data?.length?data.filter(x=>x.content_items).map(x=>`<div class="library-item" data-content-id="${esc(x.content_id)}"><div class="mini-thumb"></div><div><strong>${esc(x.content_items.title||'Saved item')}</strong><small>${esc(x.content_items.type||'Content')}${x.content_items.read_time_minutes?` · ${x.content_items.read_time_minutes} min`:''} · Saved</small></div><button data-unsave="${esc(x.content_id)}">♥</button></div>`).join(''):'<div class="library-empty">Your library is empty. Save a story, artwork or blog to see it here.</div>';area.querySelectorAll('.library-item[data-content-id]').forEach(x=>x.addEventListener('click',e=>{if(!e.target.closest('[data-unsave]'))openReader(x.dataset.contentId)}));area.querySelectorAll('[data-unsave]').forEach(b=>b.onclick=async e=>{e.stopPropagation();await supabase.from('favorites').delete().eq('user_id',user.id).eq('content_id',b.dataset.unsave);loadLibrary()})}
function setupSearch(){const input=document.querySelector('.search-row input'),button=document.querySelector('.search-row button');if(!input)return;const run=async()=>{const q=input.value.trim();if(!q){renderContent('stories',window.kolpotuliContent?.filter(x=>x.type==='story')||[],'story');return}const{data}=await supabase.from('content_items').select('id,type,title,excerpt,cover_image_url,language,read_time_minutes').eq('status','published').or(`title.ilike.%${q}%,excerpt.ilike.%${q}%`).order('published_at',{ascending:false}).limit(30);renderSearchResults(data||[],input.closest('.content-area'))};button?.addEventListener('click',run);input.addEventListener('keydown',e=>{if(e.key==='Enter')run()})}
function renderSearchResults(items,area){let box=area.querySelector('.search-results');if(!box){box=document.createElement('div');box.className='search-results';area.appendChild(box)}box.innerHTML=items.length?items.map(x=>`<button class="search-result" data-content-id="${esc(x.id)}"><span>${x.type==='art'?'◆':x.type==='blog'?'▤':'▣'}</span><span><strong>${esc(x.title)}</strong><small>${esc(x.type)}${x.read_time_minutes?` · ${x.read_time_minutes} min`:''}</small></span></button>`).join(''):'<div class="widget-sub" style="padding:10px">No matching published content.</div>';box.classList.add('show');box.querySelectorAll('[data-content-id]').forEach(b=>b.onclick=()=>openReader(b.dataset.contentId))}
async function boot(){const{data:{session}}=await supabase.auth.getSession();document.documentElement.dataset.auth=session?'signed-in':'signed-out';await loadContent();document.querySelectorAll('.search-row').forEach(()=>setupSearch());if(session)await loadLibrary();supabase.auth.onAuthStateChange(async(_event,newSession)=>{document.documentElement.dataset.auth=newSession?'signed-in':'signed-out';if(newSession)await loadLibrary();await renderRecent()})}
boot();