const desktop=document.getElementById('desktop');
const windows=[...document.querySelectorAll('.app-window')];
let z=20;
function openWindow(id){const el=document.getElementById(id);if(!el)return;el.classList.remove('hidden');z++;el.style.zIndex=z;}
function closeWindow(id){document.getElementById(id)?.classList.add('hidden');}
document.addEventListener('click',e=>{const t=e.target.closest('[data-window]');if(t){e.preventDefault();openWindow(t.dataset.window)}const c=e.target.closest('[data-close]');if(c){e.preventDefault();closeWindow(c.dataset.close)}});
windows.forEach(w=>w.addEventListener('mousedown',()=>{z++;w.style.zIndex=z}));
function updateClock(){const n=new Date();const time=new Intl.DateTimeFormat('en-IN',{hour:'numeric',minute:'2-digit',hour12:true}).format(n);const date=new Intl.DateTimeFormat('en-IN',{weekday:'long',day:'numeric',month:'long'}).format(n);document.getElementById('clockTime')?.replaceChildren(time);document.getElementById('menuTime')?.replaceChildren(time);document.getElementById('clockDate')?.replaceChildren(date)}
updateClock();setInterval(updateClock,1000);
const lang=document.getElementById('languageToggle');if(lang)lang.addEventListener('click',()=>{const bn=document.documentElement.lang!=='bn';document.documentElement.lang=bn?'bn':'en';lang.textContent=bn?'বাংলা / EN':'EN / বাংলা'});
const wallpapers={main:"url('assets/wallpapers/kolpotuli-main.svg')",dusk:"url('assets/wallpapers/kolpotuli-dusk.svg')",paper:"url('assets/wallpapers/kolpotuli-paper.svg')"};
if(!localStorage.getItem('kolpotuli-wallpaper-v2')){localStorage.setItem('kolpotuli-wallpaper','main');localStorage.setItem('kolpotuli-wallpaper-v2','1')}
const saved=localStorage.getItem('kolpotuli-wallpaper')||'main';if(desktop)desktop.style.setProperty('--wallpaper',wallpapers[saved]||wallpapers.main);
document.querySelectorAll('[data-wallpaper]').forEach(b=>b.addEventListener('click',()=>{const k=b.dataset.wallpaper;if(!wallpapers[k]||!desktop)return;desktop.style.setProperty('--wallpaper',wallpapers[k]);localStorage.setItem('kolpotuli-wallpaper',k);document.querySelectorAll('[data-wallpaper]').forEach(x=>x.classList.toggle('selected',x===b))}));
document.querySelector(`[data-wallpaper="${saved}"]`)?.classList.add('selected');
const style=document.createElement('style');style.textContent=`.settings-window{width:520px;left:50%;top:12%;transform:translateX(-50%);z-index:50}.settings-window h2{margin:0;color:var(--navy);font-size:25px}.settings-intro{margin:5px 0 22px;opacity:.65}.settings-window h3{font-size:12px;letter-spacing:.08em;text-transform:uppercase;margin:18px 0 10px;color:var(--teal)}.wallpaper-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.wallpaper-card{padding:8px;border:1px solid rgba(20,32,42,.12);border-radius:14px;background:rgba(255,255,255,.45);color:var(--ink);text-align:left;box-shadow:0 8px 20px rgba(20,32,42,.08);transition:.18s}.wallpaper-card:hover,.wallpaper-card.selected{transform:translateY(-3px);border-color:var(--gold);box-shadow:0 12px 24px rgba(20,32,42,.14)}.wallpaper-preview{display:block;height:78px;border-radius:9px;margin-bottom:8px;background-size:cover;background-position:center}.main-preview{background-image:url('../assets/wallpapers/kolpotuli-main.svg')}.dusk-preview{background-image:url('../assets/wallpapers/kolpotuli-dusk.svg')}.paper-preview{background-image:url('../assets/wallpapers/kolpotuli-paper.svg')}.wallpaper-card strong,.wallpaper-card small{display:block}.wallpaper-card strong{font-size:12px}.wallpaper-card small{font-size:10px;opacity:.62;margin-top:2px}@media(max-width:800px){.settings-window{width:100%!important;left:auto;top:auto;transform:none}}`;document.head.appendChild(style);
const play=document.querySelector('.music-controls .play');if(play)play.addEventListener('click',()=>{play.classList.toggle('playing');play.textContent=play.classList.contains('playing')?'Ⅱ':'▶'});