import { supabase } from './supabase.js';

const modal=document.createElement('div');
modal.className='auth-modal hidden';
modal.innerHTML=`<div class="auth-backdrop" data-auth-close></div><section class="auth-card glass"><button class="auth-x" data-auth-close>×</button><div class="auth-mark">ক</div><h2 id="auth-title">Welcome back</h2><p id="auth-copy">Sign in to save stories, build your library and keep your reading history.</p><form id="auth-form"><input id="auth-email" type="email" required placeholder="Email"><input id="auth-password" type="password" required minlength="6" placeholder="Password"><button class="auth-primary" type="submit" id="auth-submit">Sign in</button></form><button class="auth-secondary" id="auth-switch">Create an account</button><div class="auth-divider"><span>or</span></div><button class="auth-secondary" id="auth-guest">Continue as guest</button><div id="auth-status"></div></section>`;
document.body.append(modal);
const style=document.createElement('style');style.textContent=`.auth-modal{position:fixed;inset:0;z-index:9999;display:grid;place-items:center}.auth-modal.hidden{display:none}.auth-backdrop{position:absolute;inset:0;background:rgba(3,15,24,.58);backdrop-filter:blur(8px)}.auth-card{position:relative;width:min(420px,calc(100% - 30px));padding:30px;border-radius:24px;color:#fff;background:rgba(12,35,52,.9);border:1px solid rgba(255,255,255,.2);box-shadow:0 30px 90px rgba(0,0,0,.45)}.auth-x{position:absolute;right:15px;top:10px;font-size:26px;opacity:.7}.auth-mark{width:48px;height:48px;border-radius:15px;display:grid;place-items:center;background:#f4b52c;color:#10283d;font:700 26px "Noto Serif Bengali",serif;margin-bottom:16px}.auth-card h2{margin:0 0 7px;font-size:25px}.auth-card p{margin:0 0 20px;opacity:.72;line-height:1.5}.auth-card form{display:grid;gap:10px}.auth-card input{padding:13px 14px;border-radius:11px;border:1px solid rgba(255,255,255,.16);background:rgba(255,255,255,.08);color:#fff;outline:0}.auth-card input::placeholder{color:#fff9}.auth-primary,.auth-secondary{width:100%;padding:12px;border-radius:11px;font-weight:700;cursor:pointer}.auth-primary{background:#f4b52c;color:#10283d}.auth-secondary{margin-top:10px;background:rgba(255,255,255,.08);color:#fff;border:1px solid rgba(255,255,255,.12)}.auth-divider{display:flex;align-items:center;gap:10px;margin:18px 0 4px;opacity:.45}.auth-divider:before,.auth-divider:after{content:"";height:1px;background:#fff3;flex:1}.auth-divider span{font-size:11px}.auth-card #auth-status{min-height:20px;margin-top:12px;font-size:12px;opacity:.8}`;document.head.append(style);
let signup=false;
const title=document.getElementById('auth-title'),copy=document.getElementById('auth-copy'),submit=document.getElementById('auth-submit'),sw=document.getElementById('auth-switch'),status=document.getElementById('auth-status');
function render(){title.textContent=signup?'Create your Kolpotuli account':'Welcome back';copy.textContent=signup?'Join Kolpotuli and keep your library, favorites and reading progress with you.':'Sign in to save stories, build your library and keep your reading history.';submit.textContent=signup?'Create account':'Sign in';sw.textContent=signup?'Already have an account? Sign in':'Create an account'}
export function openAuth(){modal.classList.remove('hidden');status.textContent='';render()}
export function closeAuth(){modal.classList.add('hidden')}
modal.addEventListener('click',e=>{if(e.target.matches('[data-auth-close]'))closeAuth()});
sw.onclick=()=>{signup=!signup;render()};
document.getElementById('auth-guest').onclick=closeAuth;
document.getElementById('auth-form').onsubmit=async e=>{e.preventDefault();status.textContent='Working…';const email=document.getElementById('auth-email').value.trim(),password=document.getElementById('auth-password').value;let result=signup?await supabase.auth.signUp({email,password}):await supabase.auth.signInWithPassword({email,password});if(result.error){status.textContent=result.error.message;return}if(signup){status.textContent=result.data.session?'Account created.':'Check your email to confirm your account.'}else{closeAuth();window.dispatchEvent(new CustomEvent('kolpotuli-auth-changed',{detail:result.data.user}))}};
export async function refreshAuthUI(){const{data:{user}}=await supabase.auth.getUser();document.querySelectorAll('[data-auth-action]').forEach(b=>{b.textContent=user?'Profile':'Sign in';b.dataset.window=user?'profile':'auth'});return user}
supabase.auth.onAuthStateChange(()=>window.dispatchEvent(new Event('kolpotuli-auth-changed')));